#!/bin/bash

# GIVE THE ABSOLUTE PATH REFERENCE OF THE SERVICE CONFIG FILE.
export SRV_CONFIG_FILE="YOUR_PATH\infra\service.dev.yaml"
# GIVE THE ABSOLUTE PATH REFERENCE OF THE FOLDER CONTAINING THE CLOUD-RUN SOURCE CODE.
export APP_SOURCE_PATH="YOUR_PATH"
# GIVE THE ABSOLUTE PATH REFERENCE OF THE FOLDER CONTAINING THE CLOUD-RUN DOCKERFILE.
export DOCKERFILE="YOUR_PATH\Dockerfile"
# REPRESENTS THE PORT NUMBER ON WHERE CLOUD-RUN EMULATOR SHOULD RUN.
# SHOULD MATCH THE APPLICATION PORT NUMBER WHEN APPLICATION RAN LOCALLY.
# SHOULD MATCH THE PORT NUMBER USED WHILE CONFIGURING THE PUSH-ENDPOINT IN PUB/SUB EMULATOR
export CLOUD_RUN_EMULATOR_APP_PORT=8080